# Generated by Django 5.0.1 on 2024-02-11 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0008_remove_followers_user_remove_likepost_post_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='likepost',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
