# Generated by Django 5.0.1 on 2024-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0009_remove_followers_followed_user_remove_likepost_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
