# Generated by Django 5.0.1 on 2024-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(max_length=255),
        ),
    ]
